variables:
  CONTAINER_NAME: "$CI_PROJECT_NAME-container" # container name, e.g. mycontainer
  CONFIGURATION_LOCATION: "$CI_PROJECT_DIR/container/Dockerfile" # container configuration, e.g. packages/Dockerfile
  CONTAINER_VERSION: "latest" # container version, e.g. 1.0.0

build_docker_container:
  stage: build
  tags:
    - build
    - push
  image:
    name: gitlab.nccs.nasa.gov:5050/nccs-ci/nccs-containers/gcc/nccs-centos7-gcc8
    entrypoint: [""]
  allow_failure: false
  dependencies: []
  script:
    - pip install hpccm


